# Generated by Django 5.0.7 on 2024-07-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('preferred_name', models.CharField(default='', max_length=50)),
                ('tax_number', models.CharField(max_length=9)),
                ('date_of_birth', models.DateField()),
                ('date_of_hire', models.DateField()),
                ('date_of_termination', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('work_email', models.CharField(max_length=50)),
            ],
        ),
    ]
