# Generated by Django 5.0.7 on 2024-07-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_detail_address_alter_detail_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
