# Generated by Django 5.0.7 on 2024-07-20 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_detail_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='is_current',
            new_name='is_active',
        ),
    ]
