# Generated by Django 5.0.7 on 2024-07-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate_type',
            field=models.IntegerField(choices=[(2080, 'Hourly'), (260, 'Daily'), (52, 'Weekly'), (26, 'Fortnightly'), (13, 'Fourweekly'), (12, 'Monthly'), (1, 'Annual')], default=2080),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('employee', 'effective_date')},
        ),
    ]
