# Generated by Django 5.0.7 on 2024-07-21 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0006_alter_profile_rate_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rate_type',
            new_name='unit_type',
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_type', models.IntegerField(choices=[(2080, 'Hourly'), (260, 'Daily'), (52, 'Weekly'), (26, 'Fortnightly'), (13, 'Fourweekly'), (12, 'Monthly'), (1, 'Annual')], default=2080)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.detail')),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ratetype')),
            ],
            options={
                'unique_together': {('employee', 'effective_date', 'rate_type')},
            },
        ),
    ]
