# Generated by Django 5.0.7 on 2024-07-24 05:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_customfield'),
        ('employee', '0007_rename_rate_type_profile_unit_type_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_date', models.DateField(blank=True, default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.detail')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.customfield')),
            ],
            options={
                'unique_together': {('detail', 'field', 'effective_date')},
            },
        ),
    ]
