# Generated by Django 5.0.7 on 2024-07-24 05:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_additionaldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField()),
                ('effective_date', models.DateField(blank=True, default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.detail')),
            ],
            options={
                'unique_together': {('detail', 'value', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='AdditionalNumberDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('effective_date', models.DateField(blank=True, default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.detail')),
            ],
            options={
                'unique_together': {('detail', 'value', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='AdditionalTextDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('effective_date', models.DateField(blank=True, default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.detail')),
            ],
            options={
                'unique_together': {('detail', 'value', 'effective_date')},
            },
        ),
        migrations.DeleteModel(
            name='AdditionalDetail',
        ),
    ]
