# Generated by Django 5.0.7 on 2024-07-24 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_additionaldatedetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='effective_to',
            field=models.DateField(blank=True, default=datetime.date(9999, 12, 31)),
        ),
    ]
