# Generated by Django 5.0.7 on 2024-07-24 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_rate_effective_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='effective_to',
            field=models.DateField(blank=True, default=datetime.date(9999, 12, 31)),
        ),
    ]
