# Generated by Django 5.0.7 on 2024-09-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_allowance_unit_type'),
        ('employee', '0012_profile_effective_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaldatedetail',
            old_name='detail',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='additionalnumberdetail',
            old_name='detail',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='additionaltextdetail',
            old_name='detail',
            new_name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='additionaldatedetail',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='additionalnumberdetail',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='additionaltextdetail',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='additionaldatedetail',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='additionalnumberdetail',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='additionaltextdetail',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='additionaldatedetail',
            unique_together={('employee', 'field', 'effective_date')},
        ),
        migrations.AlterUniqueTogether(
            name='additionalnumberdetail',
            unique_together={('employee', 'field', 'effective_date')},
        ),
        migrations.AlterUniqueTogether(
            name='additionaltextdetail',
            unique_together={('employee', 'field', 'effective_date')},
        ),
    ]
