# Generated by Django 5.0.7 on 2024-10-02 03:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_allowance_unit_type'),
        ('employee', '0013_rename_detail_additionaldatedetail_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('effective_to', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('cycle_start', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.detail')),
                ('rate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_rosters', to='company.ratetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
