# Generated by Django 5.0.7 on 2024-10-02 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_roster'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='roster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.roster'),
        ),
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('employee', 'effective_date')},
        ),
    ]
