# Generated by Django 5.0.7 on 2024-10-13 03:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_custombooleanfield'),
        ('employee', '0015_roster_roster_alter_roster_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalBooleanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('effective_to', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('value', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.detail')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.custombooleanfield')),
            ],
            options={
                'abstract': False,
                'unique_together': {('employee', 'field', 'effective_date')},
            },
        ),
    ]
