# Generated by Django 5.0.7 on 2024-10-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_additionalbooleandetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='autopay',
            field=models.BooleanField(default=False),
        ),
    ]
