# Generated by Django 5.0.7 on 2024-10-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_roster_autopay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='rate_type',
        ),
    ]
