# Generated by Django 5.0.7 on 2024-07-23 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_accumulator_allowancetype_allowance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancetype',
            name='accumulators',
        ),
        migrations.CreateModel(
            name='AccumulatorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accumulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.accumulator')),
                ('allowance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.allowancetype')),
            ],
        ),
    ]
