# Generated by Django 5.0.7 on 2024-07-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_allowancetype_accumulators'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accumulatormember',
            unique_together={('allowance_type', 'accumulator')},
        ),
    ]
