# Generated by Django 5.0.7 on 2024-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_customfield'),
        ('employee', '0009_additionaldatedetail_additionalnumberdetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomNumberField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
    ]
