# Generated by Django 5.0.7 on 2024-07-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_customdatefield_customnumberfield_customtextfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowance',
            name='unit_type',
            field=models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('QUANTITY', 'Quantity'), ('AMOUNT', 'Amount')], default='HOURS', max_length=10),
        ),
    ]
