# Generated by Django 5.0.7 on 2024-10-06 06:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_allowance_unit_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateTypeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('effective_to', models.DateField(blank=True, default=datetime.date(9999, 12, 31))),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_type', models.IntegerField(choices=[(2080, 'Hourly'), (260, 'Daily'), (52, 'Weekly'), (26, 'Fortnightly'), (13, 'Fourweekly'), (12, 'Monthly'), (1, 'Annual')], default=2080)),
                ('rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ratetype')),
            ],
            options={
                'abstract': False,
                'unique_together': {('rate_type', 'effective_date')},
            },
        ),
    ]
