# Generated by Django 5.0.7 on 2024-10-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_ratetypedefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBooleanField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
