# Generated by Django 5.0.7 on 2024-09-07 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_paygroup_frequency_alter_payperiod_frequency'),
        ('company', '0008_allowance_unit_type'),
        ('employee', '0012_profile_effective_to'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actual',
            new_name='Payslip',
        ),
    ]
