# Generated by Django 5.0.7 on 2024-10-02 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='break_end_minutes',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='break_start_minutes',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time_minutes',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time_minutes',
        ),
        migrations.AddField(
            model_name='shift',
            name='break_end',
            field=models.TimeField(default=datetime.time(12, 30)),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_start',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 30)),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 30)),
        ),
    ]
