# Generated by Django 5.0.7 on 2024-10-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_allowance_unit_type'),
        ('roster', '0002_remove_shift_break_end_minutes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rostershift',
            unique_together={('roster', 'shift', 'shift_number')},
        ),
        migrations.CreateModel(
            name='ShiftAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('H', 'Hours'), ('D', 'Days')], default='H', max_length=1)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.allowance')),
                ('rate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.ratetype')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.shift')),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='allowances',
            field=models.ManyToManyField(through='roster.ShiftAllowance', to='company.allowance'),
        ),
    ]
