# Generated by Django 5.0.7 on 2024-07-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[(52, 'Weekly'), (26, 'Fortnightly'), (13, 'Fourweekly'), (12, 'Monthly'), (4, 'Quarterly'), (1, 'Annual'), (0, 'Manual')], default=52, max_length=10, verbose_name='Standard Frequency')),
                ('period_start', models.DateField(verbose_name='Base Period Start')),
                ('period_end', models.DateField(verbose_name='Base Period End')),
                ('pay_date', models.DateField(verbose_name='Base Pay Date')),
            ],
        ),
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[(52, 'Weekly'), (26, 'Fortnightly'), (13, 'Fourweekly'), (12, 'Monthly'), (4, 'Quarterly'), (1, 'Annual'), (0, 'Manual')], default=52, max_length=10, verbose_name='Pay Frequency')),
                ('period_start', models.DateField(verbose_name='Pay Period Start')),
                ('period_end', models.DateField(verbose_name='Pay Period End')),
                ('pay_date', models.DateField(verbose_name='Pay Date')),
                ('pay_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.paygroup')),
            ],
        ),
    ]
