# Generated by Django 5.0.7 on 2024-07-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygroup',
            name='frequency',
            field=models.IntegerField(choices=[(52, 'Weekly'), (26, 'Fortnightly'), (13, 'Fourweekly'), (12, 'Monthly'), (4, 'Quarterly'), (1, 'Annual'), (0, 'Manual')], default=52, verbose_name='Standard Frequency'),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='frequency',
            field=models.IntegerField(choices=[(52, 'Weekly'), (26, 'Fortnightly'), (13, 'Fourweekly'), (12, 'Monthly'), (4, 'Quarterly'), (1, 'Annual'), (0, 'Manual')], default=52, verbose_name='Pay Frequency'),
        ),
    ]
